package br.caixa.parametrosSimulacao.combos;

import br.caixa.loterias.utils.anotacoes.IgnoreCoverageGenerated;
import gm.utils.comum.Lst;
import src.commom.utils.tempo.DataHora;

@IgnoreCoverageGenerated
public class MockConsultaCombo202306121248 {

	
	

	public static MockConsultaComboMain o = new MockConsultaComboMain(DataHora.build(2023,6,12,12,48));

	static {
		exec0();
	}

	private static void exec0() {
		o.principal = new ConsultaComboPrincipalDto();
		o.principal.versao = "2.93.21";
		o.principal.payload = new Lst<>();
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 1;
		o.principal.payload.getLast().tipoCombo.nome = "Especial";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo apostas para o concurso especial vigente.            ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mega-Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Mega da Virada";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5216;
		o.principal.payload.getLast().valor = 5.00;
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 9;
		o.principal.payload.getLast().tipoCombo.nome = "Fezinha do Mês";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo a quantidade máxima de teimosinhas de todas as \r\nmodalidades disponíveis, exceto Timemania e Loteca.       ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mega-Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Mega da Virada";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5216;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 9;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mais Milionária";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 5;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 241;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 16;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Lotomania";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 12;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 50;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 4731;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 11;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Dia de Sorte";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 12;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1187;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Super Sete";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 12;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 641;
		o.principal.payload.getLast().valor = 167.00;
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 10;
		o.principal.payload.getLast().tipoCombo.nome = "Combo Vip";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo apostas múltiplas para as modalidades mais vendidas do Brasil! ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mega-Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Mega da Virada";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 9;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5216;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 9;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mais Milionária";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 8;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 241;
		o.principal.payload.getLast().valor = 924.00;
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 8;
		o.principal.payload.getLast().tipoCombo.nome = "Sorte de Hoje";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo todas as modalidades sorteadas no dia de Hoje. ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mega-Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Mega da Virada";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5216;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 8;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Lotofácil";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Lotofácil da Independência";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 15;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1170;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 3;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Quina";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Quina de São João";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 5;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 6543;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 18;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Dupla Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Dupla de Páscoa";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5052;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 16;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Lotomania";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 50;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 4731;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 20;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Timemania";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 10;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 2717;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 11;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Dia de Sorte";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1187;
		o.principal.payload.getLast().valor = 25.00;
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 6;
		o.principal.payload.getLast().tipoCombo.nome = "Chance Todo Dia";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo apostas para todas as modalidades disponíveis, incluindo teimosinhas para uma semana. ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mega-Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Mega da Virada";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5216;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 8;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Lotofácil";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Lotofácil da Independência";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 15;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1170;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 3;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Quina";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Quina de São João";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 5;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 6543;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 18;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Dupla Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Dupla de Páscoa";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5052;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 9;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mais Milionária";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 4;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 241;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 16;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Lotomania";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 50;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 4731;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 20;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Timemania";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 10;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 2717;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 11;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Dia de Sorte";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1187;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Super Sete";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 641;
		o.principal.payload.getLast().valor = 124.00;
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 7;
		o.principal.payload.getLast().tipoCombo.nome = "Sorte Acumulada";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo apostas para todas as modalidades cujo prêmio está acumulado, incluindo o concurso especial vigente. ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mega-Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Mega da Virada";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5216;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 8;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Lotofácil";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Lotofácil da Independência";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 15;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1170;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 3;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Quina";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Quina de São João";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 5;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 6543;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 18;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Dupla Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Dupla de Páscoa";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5052;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 11;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Dia de Sorte";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1187;
		o.principal.payload.getLast().valor = 15.50;
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 3;
		o.principal.payload.getLast().tipoCombo.nome = "Milionário";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo apostas para concursos com prêmios acima de R$ 1,5 milhão, incluindo o concurso especial vigente. ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mega-Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Mega da Virada";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5216;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Super Sete";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 641;
		o.principal.payload.getLast().valor = 50.00;
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 4;
		o.principal.payload.getLast().tipoCombo.nome = "Muito Dinheiro";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo apostas para concursos com prêmios acima de R$ 200 mil, incluindo o concurso especial vigente. ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mega-Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Mega da Virada";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5216;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 9;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mais Milionária";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 241;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Super Sete";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 641;
		o.principal.payload.getLast().valor = 13.50;
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 5;
		o.principal.payload.getLast().tipoCombo.nome = "Sorte Fácil";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo apostas das modalidades Dia de Sorte, Lotofácil e Quina.! ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 8;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Lotofácil";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Lotofácil da Independência";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 8;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 15;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1170;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 16;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Lotomania";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 50;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 4731;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 11;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Dia de Sorte";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1187;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Super Sete";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 4;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 641;
		o.principal.payload.getLast().valor = 55.00;
		o.principal.payload.add(new ConsultarCombosOutDto());
		o.principal.payload.getLast().tipoCombo = new TipoComboDto();
		o.principal.payload.getLast().tipoCombo.codigo = 11;
		o.principal.payload.getLast().tipoCombo.nome = "Loterias Pra Elas";
		o.principal.payload.getLast().tipoCombo.descricao = "Pacote contendo apostas para o concurso disponiveis das seguintes modalidades : +Milionária / Mega Sena / Lotofácil / Dupla Sena / Dia de Sorte.! ";
		o.principal.payload.getLast().tipoCombo.novo = false;
		o.principal.payload.getLast().modalidadesCombo = new Lst<>();
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 2;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mega-Sena";
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricaoEspecial = "Mega da Virada";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "ESPECIAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 5216;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 9;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Mais Milionária";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 6;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 241;
		o.principal.payload.getLast().modalidadesCombo.add(new ModalidadesComboDto());
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade = new ModalidadeDto();
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.valor = 11;
		o.principal.payload.getLast().modalidadesCombo.getLast().modalidade.descricao = "Dia de Sorte";
		o.principal.payload.getLast().modalidadesCombo.getLast().tipoConcurso = "NORMAL";
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeApostas = 1;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeTeimosinhas = 0;
		o.principal.payload.getLast().modalidadesCombo.getLast().quantidadeDezenas = 7;
		o.principal.payload.getLast().modalidadesCombo.getLast().numero = 1187;
		o.principal.payload.getLast().valor = 13.50;
	}
}
