package gm.utils.test.strings;

import org.junit.Test;

import js.support.console;
import src.commom.utils.string.StringCompare;
import src.commom.utils.string.StringToConstantName;

public class StringToConstantNameTest {

	@Test
	public void exec() {
		main(null);
	}

	public static void main(String[] args) {
		test("email", "EMAIL");
		test("26239 - UNIVERSIDADE FEDERAL DO PARA", "_26239_UNIVERSIDADE_FEDERAL_DO_PARA");
		test("aguardandoAprovacaoDoGerenteGeralEDiretores", "AGUARDANDO_APROVACAO_DO_GERENTE_GERAL_E_DIRETORES");
		test("26201 - COLEGIO PEDRO II", "_26201_COLEGIO_PEDRO_II");
		test("21000 - COMANDO DA AERONAUTICA", "_21000_COMANDO_DA_AERONAUTICA");
		test("45205 - FUND, INST, BRASIL, GEOG, E ESTATISTICA", "_45205_FUND_INST_BRASIL_GEOG_E_ESTATISTICA");
		test("36205 - FUNDACAO NACIONAL DE SAUDE", "_36205_FUNDACAO_NACIONAL_DE_SAUDE");
		test("26277 - FUNDACAO UNIV, FEDERAL DE OURO PRETO", "_26277_FUNDACAO_UNIV_FEDERAL_DE_OURO_PRETO");
		test("26274 - FUNDACAO UNIV, FEDERAL DE UBERLANDIA", "_26274_FUNDACAO_UNIV_FEDERAL_DE_UBERLANDIA");
		test("40803 - GOVERNO DO EX-TERRITORIO DE RONDONIA", "_40803_GOVERNO_DO_EX_TERRITORIO_DE_RONDONIA");
		test("40804 - GOVERNO DO EX-TERRITORIO DE RORAIMA", "_40804_GOVERNO_DO_EX_TERRITORIO_DE_RORAIMA");
		test("40801 - GOVERNO DO EX-TERRITORIO DO AMAPA", "_40801_GOVERNO_DO_EX_TERRITORIO_DO_AMAPA");
		test("40701 - INST, BR, MEIO AMB, REC, NAT, RENOVAVEIS", "_40701_INST_BR_MEIO_AMB_REC_NAT_RENOVAVEIS");
		test("26403 - INSTITUTO FEDERAL DO AMAZONAS", "_26403_INSTITUTO_FEDERAL_DO_AMAZONAS");
		test("30204 - INSTITUTO NAC, DA PROPRIEDADE INDUSTRIAL", "_30204_INSTITUTO_NAC_DA_PROPRIEDADE_INDUSTRIAL");
		test("57202 - INSTITUTO NACIONAL DE SEGURO SOCIAL", "_57202_INSTITUTO_NACIONAL_DE_SEGURO_SOCIAL");
		test("40108 - MINISTERIO DA CIENCIA E TECNOLOGIA", "_40108_MINISTERIO_DA_CIENCIA_E_TECNOLOGIA");
		test("17000 - MINISTERIO DA FAZENDA", "_17000_MINISTERIO_DA_FAZENDA");
		test("25000 - MINISTERIO DA SAUDE", "_25000_MINISTERIO_DA_SAUDE");
		test("49000 - MINISTERIO DOS TRANSPORTES", "_49000_MINISTERIO_DOS_TRANSPORTES");
		test("40805 - ORGAO 40805", "_40805_ORGAO40805");
		test("26269 - UNIVERSIDADE DO RIO DE JANEIRO", "_26269_UNIVERSIDADE_DO_RIO_DE_JANEIRO");
		test("26248 - UNIVERSIDADE FEDERAL RURAL DE PERNAMBUCO", "_26248_UNIVERSIDADE_FEDERAL_RURAL_DE_PERNAMBUCO");
		test("13000 - MINIST.DA AGRICULTURA,PECUARIA E ABAST.", "_13000_MINIST_DA_AGRICULTURA_PECUARIA_E_ABAST");
		test("15000 - MINISTERIO DA EDUCACAO", "_15000_MINISTERIO_DA_EDUCACAO");
		test("16000 - COMANDO DO EXERCITO", "_16000_COMANDO_DO_EXERCITO");
		test("órgão", "ORGAO");
		test("", "");
		test(null, null);
	}

	private static void test(String s, String esperado) {
		String x = StringToConstantName.exec(s);
		if (!StringCompare.eq(x, esperado)) {
			console.log(x);
			console.log(esperado);
			throw new RuntimeException();
		}
	}

}
